services:
  - type: web
    name: mans_store
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python manage.py create_admin
    startCommand: gunicorn config.wsgi:application
