# Generated by Django 5.2.5 on 2025-08-15 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('category', models.CharField(blank=True, choices=[('جديد', 'جديد'), ('مستعمل', 'مستعمل'), ('ألعاب', 'ألعاب'), ('حواسيب', 'حواسيب'), ('ملحقات', 'ملحقات')], max_length=20, verbose_name='التصنيف')),
                ('badge', models.CharField(blank=True, max_length=50, verbose_name='شارة البطاقة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('details', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('image', models.ImageField(upload_to='products/', verbose_name='الصورة')),
                ('store_url', models.URLField(verbose_name='رابط صفحة المنتج في المتجر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='عُدّل في')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'منتجات',
                'ordering': ('-created_at',),
            },
        ),
    ]
