# Generated by Django 5.2.5 on 2025-08-15 23:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{8,15}$', 'رقم الجوال غير صحيح')], verbose_name='رقم الجوال')),
                ('account_number', models.CharField(max_length=34, verbose_name='رقم الحساب (نفس العميل)')),
                ('transaction_ref', models.CharField(blank=True, max_length=100, verbose_name='رقم العملية (اختياري)')),
                ('proof_image', models.ImageField(blank=True, upload_to='proofs/', verbose_name='إرفاق صورة إثبات الشراء (اختياري)')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء')),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المستحق بعد 30%')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_requests', to='products.product')),
            ],
            options={
                'verbose_name': 'طلب بيع الجهاز بعد الشراء',
                'verbose_name_plural': 'طلبات بيع الجهاز بعد الشراء',
                'ordering': ('-created_at',),
            },
        ),
    ]
