# Generated by Django 5.2.5 on 2025-08-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sellrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrequest',
            name='bank_name',
            field=models.CharField(default='الراجحي', max_length=100),
            preserve_default=False,
        ),
    ]
